-- ==============================================================
-- Government Saint Louis — ПОЛНЫЙ СКРИПТ БАЗЫ ДАННЫХ
-- Запускайте один раз в Supabase SQL Editor (или блоками по порядку)
-- ==============================================================


-- ==============================================================
-- БЛОК 1: РАСШИРЕНИЯ
-- ==============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ==============================================================
-- БЛОК 2: ТАБЛИЦЫ
-- ==============================================================

-- Юридические заявления
CREATE TABLE IF NOT EXISTS public.lawyer_statements (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz  default timezone('utc', now()) not null,
  char_name     text         not null,
  char_age      integer      not null,
  vk_link       text         not null,
  biography     text         not null,
  about_oop     text         not null,
  what_oop      text         not null,
  oop_order     text         not null,
  status        text         default 'На рассмотрении' not null,
  admin_comment text         default '',
  checked_by    text         default '',
  user_ip       text         default ''
);

-- Администраторы (пароли хранятся как SHA-256 хэши)
CREATE TABLE IF NOT EXISTS public.admin_users (
  id       bigint generated by default as identity primary key,
  username text not null unique,
  password text not null
);

-- Заблокированные IP-адреса
CREATE TABLE IF NOT EXISTS public.banned_ips (
  id         bigint generated by default as identity primary key,
  ip         text not null unique,
  created_at timestamptz default now()
);

-- Лог действий администраторов
CREATE TABLE IF NOT EXISTS public.admin_logs (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  admin_login   text,
  statement_id  bigint,
  action_type   text,
  admin_comment text,
  admin_ip      text
);

-- Фракции (с балансом State Coins)
CREATE TABLE IF NOT EXISTS public.factions (
  id         bigserial primary key,
  name       text   not null unique,
  sc_balance bigint not null default 100000
);

-- Лидеры фракций (для авторизации на сайте)
CREATE TABLE IF NOT EXISTS public.leader_users (
  id         bigserial primary key,
  username   text   not null unique,
  password   text   not null,
  faction_id bigint references public.factions(id) on delete set null,
  created_at timestamptz default now()
);

-- Заявки и отчёты лидеров (SC-предложения)
CREATE TABLE IF NOT EXISTS public.sc_proposals (
  id                 bigserial primary key,
  created_at         timestamptz default now(),
  sender_login       text        not null,
  faction_id         bigint      references public.factions(id),
  type               text        not null, -- 'МФ_Бой', 'МФ_Тренировка', 'Задание', 'Викторина'
  details            text        not null,
  fund               bigint      not null default 0,
  winner_faction_id  bigint      references public.factions(id),
  with_faction_id    bigint      references public.factions(id),
  evidence_link      text        not null,
  status             text        not null default 'На рассмотрении',
  admin_comment      text,
  checked_by         text
);

-- Вопросы дня (интеллектуальная викторина)
CREATE TABLE IF NOT EXISTS public.daily_questions (
  id                bigserial primary key,
  created_at        timestamptz default now(),
  question_text     text        not null,
  reward            bigint      not null default 2500,
  is_active         boolean     not null default true,
  winner_faction_id bigint      references public.factions(id)
);

-- История изменений балансов
CREATE TABLE IF NOT EXISTS public.balance_history (
  id            bigserial primary key,
  created_at    timestamptz default now(),
  fraction_name text        not null,
  action_type   text        not null,
  amount_change bigint      not null, -- положительное или отрицательное
  description   text
);


-- ==============================================================
-- БЛОК 3: НАЧАЛЬНЫЕ ДАННЫЕ
-- ==============================================================

-- Фракции
INSERT INTO public.factions (name) VALUES
  ('SFPD'), ('LSPD'), ('LVPD'), ('FBI'),
  ('Army SF'), ('Army LV'), ('Government'), ('Medic')
ON CONFLICT (name) DO NOTHING;

-- Лидеры фракций (временные пароли)
DELETE FROM public.leader_users WHERE username LIKE 'Leader_%';
INSERT INTO public.leader_users (username, password, faction_id) VALUES
  ('Leader_LSPD',       encode(digest('ACTIVATE_LSPD_111', 'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'LSPD')),
  ('Leader_LVPD',       encode(digest('ACTIVATE_LVPD_222', 'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'LVPD')),
  ('Leader_FBI',        encode(digest('ACTIVATE_FBI_333',  'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'FBI')),
  ('Leader_ArmySF',     encode(digest('ACTIVATE_ASF_444',  'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'Army SF')),
  ('Leader_ArmyLV',     encode(digest('ACTIVATE_ALV_555',  'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'Army LV')),
  ('Leader_Gov',        encode(digest('ACTIVATE_Gov_111',  'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'Government')),
  ('Leader_Medic',      encode(digest('ACTIVATE_MED_777',  'sha256'), 'hex'), (SELECT id FROM public.factions WHERE name = 'Medic'))
ON CONFLICT (username) DO NOTHING;


-- ==============================================================
-- БЛОК 4: ROW LEVEL SECURITY (RLS)
-- ==============================================================
ALTER TABLE public.banned_ips        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lawyer_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.factions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leader_users      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sc_proposals      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_questions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.balance_history   ENABLE ROW LEVEL SECURITY;

-- Сбрасываем старые политики
DROP POLICY IF EXISTS "Allow anon read bans"              ON public.banned_ips;
DROP POLICY IF EXISTS "Allow anon insert statements"      ON public.lawyer_statements;
DROP POLICY IF EXISTS "Allow anon read statements"        ON public.lawyer_statements;
DROP POLICY IF EXISTS "Allow public select on factions"   ON public.factions;
DROP POLICY IF EXISTS "Allow anon read factions"          ON public.factions;
DROP POLICY IF EXISTS "Allow anon read leader_users"      ON public.leader_users;
DROP POLICY IF EXISTS "Allow anon insert proposals"       ON public.sc_proposals;
DROP POLICY IF EXISTS "Allow anon read proposals"         ON public.sc_proposals;
DROP POLICY IF EXISTS "Allow public insert on sc_proposals"   ON public.sc_proposals;
DROP POLICY IF EXISTS "Allow public read to sc_proposals"     ON public.sc_proposals;
DROP POLICY IF EXISTS "Allow public inserts to sc_proposals"  ON public.sc_proposals;
DROP POLICY IF EXISTS "Allow anon read questions"         ON public.daily_questions;
DROP POLICY IF EXISTS "Allow public select on daily_questions" ON public.daily_questions;
DROP POLICY IF EXISTS "Allow public read access to balance_history" ON public.balance_history;
DROP POLICY IF EXISTS "Allow public insert on lawyer_statements"    ON public.lawyer_statements;

-- Разрешения на чтение (для сайта и публичных страниц)
CREATE POLICY "Allow anon read bans"          ON public.banned_ips       FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon read statements"    ON public.lawyer_statements FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert statements"  ON public.lawyer_statements FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon read factions"      ON public.factions         FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon read leader_users"  ON public.leader_users     FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon read proposals"     ON public.sc_proposals     FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert proposals"   ON public.sc_proposals     FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon read questions"     ON public.daily_questions  FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon read history"       ON public.balance_history  FOR SELECT TO anon USING (true);
-- admin_users остаётся закрытой для анонимных пользователей (без политик SELECT для anon)


-- ==============================================================
-- БЛОК 5: ТРИГГЕР — АНТИСПАМ И ПРОВЕРКА БАНА
-- ==============================================================
CREATE OR REPLACE FUNCTION public.check_user_ban_status()
RETURNS TRIGGER AS $$
BEGIN
  -- Проверка бана по IP
  IF EXISTS (SELECT 1 FROM public.banned_ips WHERE ip = NEW.user_ip) THEN
    RAISE EXCEPTION 'Доступ ограничен: данный IP-адрес заблокирован администрацией.'
    USING ERRCODE = '42501';
  END IF;

  -- Антиспам: не чаще одного заявления в 10 минут с одного IP или под одним ником
  IF EXISTS (
    SELECT 1 FROM public.lawyer_statements
    WHERE (user_ip = NEW.user_ip OR LOWER(char_name) = LOWER(NEW.char_name))
      AND created_at > NOW() - INTERVAL '10 minutes'
  ) THEN
    RAISE EXCEPTION 'Слишком много запросов! Вы можете отправлять заявление не чаще, чем раз в 10 минут.'
    USING ERRCODE = '42P10';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_check_ban ON public.lawyer_statements;
CREATE TRIGGER trigger_check_ban
BEFORE INSERT ON public.lawyer_statements
FOR EACH ROW EXECUTE FUNCTION public.check_user_ban_status();


-- ==============================================================
-- БЛОК 6: RPC — АВТОРИЗАЦИЯ АДМИНИСТРАТОРОВ
-- ==============================================================
CREATE OR REPLACE FUNCTION public.check_admin_credentials(p_login text, p_password_hash text)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE username = p_login AND password = p_password_hash
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.check_admin_credentials(text, text) TO anon;


-- ==============================================================
-- БЛОК 7: RPC — СМЕНА ВРЕМЕННОГО ПАРОЛЯ (первый вход)
-- ==============================================================
CREATE OR REPLACE FUNCTION public.set_new_password(
  p_login             text,
  p_old_password_hash text,
  p_new_password_hash text
)
RETURNS boolean AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE username = p_login AND password = p_old_password_hash
  ) THEN
    UPDATE public.admin_users
    SET password = p_new_password_hash
    WHERE username = p_login;
    RETURN true;
  ELSE
    RETURN false;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.set_new_password(text, text, text) TO anon;


-- ==============================================================
-- БЛОК 8: RPC — ОБНОВЛЕНИЕ СТАТУСА АНКЕТЫ ЮРИСТА
-- ==============================================================
DROP FUNCTION IF EXISTS public.update_statement_status_secure(bigint, text, text, text, text);
DROP FUNCTION IF EXISTS public.update_statement_status_secure(bigint, text, text, text, text, text);

CREATE OR REPLACE FUNCTION public.update_statement_status_secure(
  p_statement_id   bigint,
  p_new_status     text,
  p_comment        text,
  p_admin_login    text,
  p_admin_password text,
  p_admin_ip       text DEFAULT '—'
)
RETURNS boolean AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE username = p_admin_login AND password = p_admin_password
  ) THEN
    RAISE EXCEPTION 'Доступ запрещён: неверные учётные данные.' USING ERRCODE = '42501';
  END IF;

  UPDATE public.lawyer_statements
  SET status        = p_new_status,
      admin_comment = p_comment,
      checked_by    = p_admin_login
  WHERE id = p_statement_id;

  INSERT INTO public.admin_logs (admin_login, statement_id, action_type, admin_comment, admin_ip)
  VALUES (p_admin_login, p_statement_id, p_new_status, p_comment, p_admin_ip);

  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.update_statement_status_secure(bigint, text, text, text, text, text) TO anon;


-- ==============================================================
-- БЛОК 9: RPC — АВТОРИЗАЦИЯ ЛИДЕРОВ ФРАКЦИЙ
-- ==============================================================
DROP FUNCTION IF EXISTS public.check_leader_credentials(text, text);

CREATE OR REPLACE FUNCTION public.check_leader_credentials(p_login text, p_password_hash text)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.leader_users
    WHERE username = p_login AND password = p_password_hash
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.check_leader_credentials(text, text) TO anon;


-- ==============================================================
-- БЛОК 10: RPC — ПУБЛИКАЦИЯ ВОПРОСА ДНЯ (только Marat_Sardar)
-- ==============================================================
CREATE OR REPLACE FUNCTION public.create_daily_question_secure(
  p_question_text text,
  p_reward        integer,
  p_admin_login   text,
  p_admin_password text
)
RETURNS boolean AS $$
BEGIN
  IF p_admin_login != 'Marat_Sardar' OR NOT EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE username = p_admin_login AND password = p_admin_password
  ) THEN
    RAISE EXCEPTION 'Доступ запрещён: недостаточно прав для публикации вопросов.';
  END IF;

  -- Деактивируем предыдущий вопрос
  UPDATE public.daily_questions SET is_active = false WHERE is_active = true;

  -- Публикуем новый
  INSERT INTO public.daily_questions (question_text, reward, is_active)
  VALUES (p_question_text, p_reward, true);

  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.create_daily_question_secure(text, integer, text, text) TO anon;


-- ==============================================================
-- БЛОК 11: RPC — ОДОБРЕНИЕ / ОТКЛОНЕНИЕ SC-ЗАЯВОК
--
-- Логика распределения баланса:
--
--   МФ_Бой / МФ_Тренировка:
--     Обе фракции ставят по fund SC.
--     Победитель получает +fund (выигрывает ставку соперника).
--     Проигравший теряет  -fund (теряет свою ставку).
--     Итог: winner_balance += fund,  loser_balance -= fund
--
--   Задание:
--     Фракция-исполнитель получает +task_reward SC от правительства.
--     Проигравших нет — только начисление.
--
--   Викторина:
--     Фракция-победитель получает +fund SC.
--
-- ==============================================================
DROP FUNCTION IF EXISTS public.update_proposal_status_secure(bigint, text, text, text, text);
DROP FUNCTION IF EXISTS public.update_proposal_status_secure(bigint, text, text, text, text, integer);
DROP FUNCTION IF EXISTS public.update_proposal_status_secure(bigint, text, text, text, text, integer, bigint);
DROP FUNCTION IF EXISTS public.update_proposal_status_secure(bigint, text, text, text, text, text, text, integer);
DROP FUNCTION IF EXISTS public.update_proposal_status_secure(int,    text, text, text, text, int);

CREATE OR REPLACE FUNCTION public.update_proposal_status_secure(
  p_proposal_id         bigint,
  p_new_status          text,
  p_comment             text,
  p_admin_login         text,
  p_admin_password_hash text,
  p_task_reward         integer DEFAULT NULL,  -- заполняется только для типа «Задание»
  p_winner_name         text    DEFAULT NULL,  -- заполняется только для типа «МФ_Бой»
  p_loser_name          text    DEFAULT NULL   -- заполняется только для типа «МФ_Бой»
)
RETURNS boolean AS $$
DECLARE
  v_proposal    public.sc_proposals%ROWTYPE;
  v_winner_id   bigint;
  v_loser_id    bigint;
  v_fund        bigint;
  v_faction_row public.factions%ROWTYPE;
BEGIN
  -- 1. Авторизация
  IF NOT EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE username = p_admin_login AND password = p_admin_password_hash
  ) THEN
    RAISE EXCEPTION 'Доступ запрещён: неверные учётные данные.' USING ERRCODE = '42501';
  END IF;

  -- 2. Загружаем заявку
  SELECT * INTO v_proposal FROM public.sc_proposals WHERE id = p_proposal_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Заявка не найдена.' USING ERRCODE = 'P0002';
  END IF;

  -- 3. Если заявка уже обработана — защита от двойного нажатия
  IF v_proposal.status != 'На рассмотрении' THEN
    RAISE EXCEPTION 'Заявка уже была обработана ранее.';
  END IF;

  -- 4. Логика начисления (только при одобрении)
  IF p_new_status = 'Одобрено' THEN

    -- ── МФ_Бой / МФ_Тренировка ──────────────────────────────
    IF v_proposal.type IN ('МФ_Бой', 'МФ_Тренировка') THEN
      -- Оба имени обязательны
      IF p_winner_name IS NULL OR p_loser_name IS NULL THEN
        RAISE EXCEPTION 'Для типа «%» необходимо указать победителя и проигравшего.', v_proposal.type;
      END IF;

      -- Ищем фракции по имени
      SELECT id INTO v_winner_id FROM public.factions WHERE name = p_winner_name;
      SELECT id INTO v_loser_id  FROM public.factions WHERE name = p_loser_name;

      IF v_winner_id IS NULL THEN
        RAISE EXCEPTION 'Фракция-победитель «%» не найдена в базе.', p_winner_name;
      END IF;
      IF v_loser_id IS NULL THEN
        RAISE EXCEPTION 'Фракция-проигравший «%» не найдена в базе.', p_loser_name;
      END IF;

      v_fund := v_proposal.fund; -- ставка каждой стороны

      -- Победитель: +fund
      UPDATE public.factions SET sc_balance = sc_balance + v_fund WHERE id = v_winner_id;

      SELECT * INTO v_faction_row FROM public.factions WHERE id = v_winner_id;
      INSERT INTO public.balance_history (fraction_name, action_type, amount_change, description)
      VALUES (v_faction_row.name, v_proposal.type, v_fund,
              'Победа над ' || p_loser_name || '. ' || COALESCE(p_comment, ''));

      -- Проигравший: -fund
      UPDATE public.factions SET sc_balance = sc_balance - v_fund WHERE id = v_loser_id;

      SELECT * INTO v_faction_row FROM public.factions WHERE id = v_loser_id;
      INSERT INTO public.balance_history (fraction_name, action_type, amount_change, description)
      VALUES (v_faction_row.name, v_proposal.type, -v_fund,
              'Поражение от ' || p_winner_name || '. ' || COALESCE(p_comment, ''));

    -- ── Задание ──────────────────────────────────────────────
    ELSIF v_proposal.type = 'Задание' THEN
      -- Используем сумму, введённую Маратом вручную (или fund из заявки, если не указана)
      v_fund := COALESCE(p_task_reward, v_proposal.fund);

      UPDATE public.factions SET sc_balance = sc_balance + v_fund WHERE id = v_proposal.faction_id;

      SELECT * INTO v_faction_row FROM public.factions WHERE id = v_proposal.faction_id;
      INSERT INTO public.balance_history (fraction_name, action_type, amount_change, description)
      VALUES (v_faction_row.name, 'Задание', v_fund,
              'Выполнение гос. задания: ' || COALESCE(v_proposal.details, '') || '. ' || COALESCE(p_comment, ''));

      -- Обновляем fund в самой заявке для отчётности
      UPDATE public.sc_proposals SET fund = v_fund WHERE id = p_proposal_id;

    -- ── Викторина ─────────────────────────────────────────────
    ELSIF v_proposal.type = 'Викторина' THEN
      v_fund := v_proposal.fund;

      UPDATE public.factions SET sc_balance = sc_balance + v_fund WHERE id = v_proposal.faction_id;

      SELECT * INTO v_faction_row FROM public.factions WHERE id = v_proposal.faction_id;
      INSERT INTO public.balance_history (fraction_name, action_type, amount_change, description)
      VALUES (v_faction_row.name, 'Викторина', v_fund,
              'Правильный ответ на вопрос дня. ' || COALESCE(p_comment, ''));

    END IF;
  END IF;

  -- 5. Обновляем статус заявки
  UPDATE public.sc_proposals
  SET status        = p_new_status,
      admin_comment = p_comment,
      checked_by    = p_admin_login
  WHERE id = p_proposal_id;

  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.update_proposal_status_secure(bigint, text, text, text, text, integer, text, text) TO anon;


-- ==============================================================
-- БЛОК 12: ПРОВЕРКА — УБЕДИТЕСЬ, ЧТО ОСТАЛАСЬ РОВНО ОДНА СИГНАТУРА
-- ==============================================================
-- SELECT proname, pronargs, proargtypes::text
-- FROM pg_proc
-- WHERE proname IN ('update_proposal_status_secure', 'update_statement_status_secure')
--   AND pronamespace = 'public'::regnamespace;


-- ==============================================================
-- БЛОК 13: ПРИМЕРЫ УПРАВЛЕНИЯ АДМИНИСТРАТОРАМИ
-- (раскомментируйте нужное и выполните отдельно)
-- ==============================================================

-- Добавить нового администратора:
-- INSERT INTO public.admin_users (username, password)
-- VALUES ('New_Admin', encode(digest('ACTIVATE_NEWADMIN_001', 'sha256'), 'hex'));

-- Сбросить пароль существующему администратору:
-- UPDATE public.admin_users
-- SET password = encode(digest('ACTIVATE_RESET_111', 'sha256'), 'hex')
-- WHERE username = 'Lucky_Grek';

-- Деактивировать пользователя (удалить из таблицы):
-- DELETE FROM public.admin_users WHERE username = 'Old_Admin';
